# A configuration that can be used for simple tests involving the ci_hsc_gen3 repo.
facility_name: Subaru
obs_collection: LSST.CI
collections: ["HSC/runs/ci_hsc"]
fallback_instrument: HSC
obs_publisher_did_fmt: "ivo://org.rubinobs/usdac/hsc?repo=/repo/main&id={id}"
dataset_types:
  raw:
    dataproduct_type: image
    dataproduct_subtype: lsst.raw
    calib_level: 1
    obs_id_fmt: "{records[exposure].obs_id}"
    o_ucd: phot.count
    access_format: image/fits
    extra_columns:
      obs_title:
        template: "{dataset_type} - {band} - {records[exposure].obs_id}-{records[detector].full_name} {records[exposure].timespan.begin.utc.isot}Z"
  calexp:
    dataproduct_type: image
    dataproduct_subtype: lsst.calexp
    calib_level: 2
    obs_id_fmt: "{records[visit].name}"
    o_ucd: phot.count
    access_format: image/fits
    extra_columns:
      obs_title:
        template: "{dataset_type} - {band} - {records[visit].name}-{records[detector].full_name} {records[visit].timespan.begin.utc.isot}Z"
  deepCoadd:
    dataproduct_type: image
    dataproduct_subtype: lsst.coadd
    calib_level: 3
    obs_id_fmt: "{skymap}-{tract}-{patch}"
    o_ucd: phot.count
    access_format: image/fits
    extra_columns:
      obs_title:
        template: "{dataset_type} - {band} - tract={tract} patch={patch}"
extra_columns:
  lsst_visit:
    template: "{visit}"
    type: "int"
    doc: Visit or exposure identifier
  lsst_detector:
    template: "{detector}"
    type: "int"
    doc: Detector number of this observation
  lsst_tract:
    template: "{tract}"
    type: "int"
    doc: Tract within a skymap
  lsst_patch:
    template: "{patch}"
    type: "int"
    doc: Patch within a tract
  lsst_band:
    template: "{band}"
    type: "string"
    doc: Wavelength band for this observation
  lsst_filter:
    template: "{physical_filter}"
    type: "string"
    doc: Physical filter name for this observation
spectral_ranges:
  "HSC-G": [406.0e-9, 545.0e-9]
  "HSC-R": [543.0e-9, 693.0e-9]
  "HSC-R2": [542.0e-9, 693.0e-9]
  "HSC-I": [690.0e-9, 842.0e-9]
  "HSC-I2": [692.0e-9, 850.0e-9]
  "HSC-Z": [852.0e-9, 928.0e-9]
  "HSC-Y": [937.0e-9, 1015.0e-9]
  "N921": [914.7e-9, 928.1e-9]
  "g": [406.0e-9, 545.0e-9]
  "r": [542.0e-9, 693.0e-9]
  "i": [692.0e-9, 850.0e-9]
  "z": [852.0e-9, 928.0e-9]
  "y": [937.0e-9, 1015.0e-9]
