facility_name: Subaru
obs_collection: LSST.CI
collections: ["HSC/runs/ci_hsc"]
dataset_types:
  raw:
    dataproduct_type: image
    dataproduct_subtype: lsst.raw
    calib_level: 1
    obs_id_fmt: "{records[exposure].obs_id}"
    o_ucd: phot.count
    access_format: image/fits
  calexp:
    dataproduct_type: image
    dataproduct_subtype: lsst.calexp
    calib_level: 2
    obs_id_fmt: "{records[visit].name}"
    o_ucd: phot.count
    access_format: image/fits
  deepCoadd:
    dataproduct_type: image
    dataproduct_subtype: lsst.coadd
    calib_level: 3
    obs_id_fmt: "{skymap}-{tract}-{patch}"
    o_ucd: phot.count
    access_format: image/fits
extra_columns:
  lsst_visit:
    template: "{visit}"
    type: "int"
  lsst_detector:
    template: "{detector}"
    type: "int"
  lsst_tract:
    template: "{tract}"
    type: "int"
  lsst_patch:
    template: "{patch}"
    type: "int"
  lsst_band:
    template: "{band}"
    type: "string"
  lsst_filter:
    template: "{physical_filter}"
    type: "string"
spectral_ranges:
  "HSC-G": [406.0e-9, 545.0e-9]
  "HSC-R": [543.0e-9, 693.0e-9]
  "HSC-R2": [542.0e-9, 693.0e-9]
  "HSC-I": [690.0e-9, 842.0e-9]
  "HSC-I2": [692.0e-9, 850.0e-9]
  "HSC-Z": [852.0e-9, 928.0e-9]
  "HSC-Y": [937.0e-9, 1015.0e-9]
  "N921": [914.7e-9, 928.1e-9]
  "g": [406.0e-9, 545.0e-9]
  "r": [542.0e-9, 693.0e-9]
  "i": [692.0e-9, 850.0e-9]
  "z": [852.0e-9, 928.0e-9]
  "y": [937.0e-9, 1015.0e-9]
