facility_name: Rubin-LSST
obs_collection: LSST.DP02
collections: ["2.2i/runs/DP0.2"]
use_butler_uri: false
dataset_types:
  raw:
    dataproduct_type: image
    dataproduct_subtype: lsst.raw
    calib_level: 1
    obs_id_fmt: "{records[exposure].obs_id}-{records[detector].full_name}"
    o_ucd: phot.count
    access_format: image/fits
    datalink_url_fmt: "https://data.lsst.cloud/api/datalink/links?ID=butler%3A//dp02/{id}"
  calexp:
    dataproduct_type: image
    dataproduct_subtype: lsst.calexp
    calib_level: 2
    obs_id_fmt: "{records[visit].name}-{records[detector].full_name}"
    o_ucd: phot.count
    access_format: image/fits
    datalink_url_fmt: "https://data.lsst.cloud/api/datalink/links?ID=butler%3A//dp02/{id}"
  deepCoadd_calexp:
    dataproduct_type: image
    dataproduct_subtype: lsst.deepCoadd_calexp
    calib_level: 3
    obs_id_fmt: "{skymap}-{tract}-{patch}"
    o_ucd: phot.count
    access_format: image/fits
    datalink_url_fmt: "https://data.lsst.cloud/api/datalink/links?ID=butler%3A//dp02/{id}"
  goodSeeingCoadd:
    dataproduct_type: image
    dataproduct_subtype: lsst.goodSeeingCoadd
    calib_level: 3
    obs_id_fmt: "{skymap}-{tract}-{patch}"
    o_ucd: phot.count
    access_format: image/fits
    datalink_url_fmt: "https://data.lsst.cloud/api/datalink/links?ID=butler%3A//dp02/{id}"
  goodSeeingDiff_differenceExp:
    dataproduct_type: image
    dataproduct_subtype: lsst.goodSeeingDiff_differenceExp
    calib_level: 3
    obs_id_fmt: "{records[visit].name}-{records[detector].full_name}"
    o_ucd: phot.count
    access_format: image/fits
    datalink_url_fmt: "https://data.lsst.cloud/api/datalink/links?ID=butler%3A//dp02/{id}"
extra_columns:
  lsst_visit:
    template: "{visit}"
    type: "int"
  lsst_detector:
    template: "{detector}"
    type: "int"
  lsst_tract:
    template: "{tract}"
    type: "int"
  lsst_patch:
    template: "{patch}"
    type: "int"
  lsst_band:
    template: "{band}"
    type: "str"
  lsst_filter:
    template: "{physical_filter}"
    type: "str"
spectral_ranges:
  "u": [330.0e-9, 400.0e-9]
  "g": [402.0e-9, 552.0e-9]
  "r": [552.0e-9, 691.0e-9]
  "i": [691.0e-9, 818.0e-9]
  "z": [818.0e-9, 922.0e-9]
  "y": [970.0e-9, 1060.0e-9]
