facility_name: Rubin:Simonyi
facility_map:
  LSSTComCam: "Rubin:Simonyi"
obs_collection: LSST.DP1
collections: ["LSSTComCam/DP1"]
use_butler_uri: false
fallback_instrument: LSSTComCam
obs_publisher_did_fmt: "ivo://org.rubinobs/usdac/lsst-dp1?repo=dp1&id={id}"
dataset_types:
  raw:
    dataproduct_type: image
    dataproduct_subtype: lsst.raw
    calib_level: 1
    obs_id_fmt: "{records[exposure].obs_id}"
    o_ucd: phot.count
    access_format: "application/x-votable+xml;content=datalink"
    datalink_url_fmt: "https://data.lsst.cloud/api/datalink/links?ID=ivo%3A%2F%2Forg.rubinobs%2Flsst-dp1%3Frepo%3Ddp1%26id%3D{id}"
    s_xel: [4608, 4096]
  visit_image:
    dataproduct_type: image
    dataproduct_subtype: lsst.visit_image
    calib_level: 2
    obs_id_fmt: "{records[visit].name}"
    o_ucd: phot.flux.density
    access_format: "application/x-votable+xml;content=datalink"
    datalink_url_fmt: "https://data.lsst.cloud/api/datalink/links?ID=ivo%3A%2F%2Forg.rubinobs%2Flsst-dp1%3Frepo%3Ddp1%26id%3D{id}"
    s_xel: [4072, 4000]
  deep_coadd:
    dataproduct_type: image
    dataproduct_subtype: lsst.deep_coadd
    calib_level: 3
    obs_id_fmt: "{skymap}-{tract}-{patch}"
    o_ucd: phot.flux.density
    access_format: "application/x-votable+xml;content=datalink"
    datalink_url_fmt: "https://data.lsst.cloud/api/datalink/links?ID=ivo%3A%2F%2Forg.rubinobs%2Flsst-dp1%3Frepo%3Ddp1%26id%3D{id}"
    s_xel: [3400, 3400]
  template_coadd:
    dataproduct_type: image
    dataproduct_subtype: lsst.template_coadd
    calib_level: 3
    obs_id_fmt: "{skymap}-{tract}-{patch}"
    o_ucd: phot.flux_density
    access_format: "application/x-votable+xml;content=datalink"
    datalink_url_fmt: "https://data.lsst.cloud/api/datalink/links?ID=ivo%3A%2F%2Forg.rubinobs%2Flsst-dp1%3Frepo%3Ddp1%26id%3D{id}"
    s_xel: [3400, 3400]
  difference_image:
    dataproduct_type: image
    dataproduct_subtype: lsst.difference_image
    calib_level: 3
    obs_id_fmt: "{records[visit].name}"
    o_ucd: phot.flux.density
    access_format: "application/x-votable+xml;content=datalink"
    datalink_url_fmt: "https://data.lsst.cloud/api/datalink/links?ID=ivo%3A%2F%2Forg.rubinobs%2Flsst-dp1%3Frepo%3Ddp1%26id%3D{id}"
    s_xel: [4072, 4000]
extra_columns:
  lsst_visit:
    template: "{visit}"
    type: "int"
  lsst_detector:
    template: "{detector}"
    type: "int"
  lsst_tract:
    template: "{tract}"
    type: "int"
  lsst_patch:
    template: "{patch}"
    type: "int"
  lsst_band:
    template: "{band}"
    type: "string"
  lsst_filter:
    template: "{physical_filter}"
    type: "string"
spectral_ranges:
  "u": [300.0e-9, 393.2e-9]
  "g": [402.6e-9, 548.3e-9]
  "r": [551.0e-9, 689.1e-9]
  "i": [693.6e-9, 818.8e-9]
  "z": [819.2e-9, 920.1e-9]
  "y": [927.8e-9, 1100.0e-9]
