facility_name: Rubin:Simonyi
facility_map:
  LATISS: "Rubin:1.2m"
  LSSTComCam: "Rubin:Simonyi"
  LSSTCam: "Rubin:Simonyi"
obs_collection: LSST.Embargo
collections: [ "LSSTComCam/nightlyValidation" ] # "LSSTComCam/prompt/output-*", "LSSTComCam/runs/DRP/*/w_*/*"
use_butler_uri: false
dataset_types:
  raw:
    dataproduct_type: image
    dataproduct_subtype: lsst.raw
    calib_level: 1
    obs_id_fmt: "{records[exposure].obs_id}-{records[detector].full_name}"
    o_ucd: phot.count
    access_format: "application/x-votable+xml;content=datalink"
    datalink_url_fmt: "https://usdf-rsp.slac.stanford.edu/api/datalink/links?ID=butler%3A//embargo/{id}"
  postISRCCD:
    dataproduct_type: image
    dataproduct_subtype: lsst.postISRCCD
    calib_level: 1
    obs_id_fmt: "{records[exposure].obs_id}-{records[detector].full_name}"
    o_ucd: phot.count
    access_format: "application/x-votable+xml;content=datalink"
    datalink_url_fmt: "https://usdf-rsp.slac.stanford.edu/api/datalink/links?ID=butler%3A//embargo/{id}"
  pvi:
    dataproduct_type: image
    dataproduct_subtype: lsst.pvi
    calib_level: 1
    obs_id_fmt: "{records[visit].name}-{records[detector].full_name}"
    o_ucd: phot.count
    access_format: "application/x-votable+xml;content=datalink"
    datalink_url_fmt: "https://usdf-rsp.slac.stanford.edu/api/datalink/links?ID=butler%3A//embargo/{id}"
  calexp:
    dataproduct_type: image
    dataproduct_subtype: lsst.calexp
    calib_level: 2
    obs_id_fmt: "{records[visit].name}-{records[detector].full_name}"
    o_ucd: phot.count
    access_format: "application/x-votable+xml;content=datalink"
    datalink_url_fmt: "https://usdf-rsp.slac.stanford.edu/api/datalink/links?ID=butler%3A//embargo/{id}"
  deepCoadd:
    dataproduct_type: image
    dataproduct_subtype: lsst.deepCoadd
    calib_level: 3
    obs_id_fmt: "{skymap}-{tract}-{patch}"
    o_ucd: phot.count
    access_format: "application/x-votable+xml;content=datalink"
    datalink_url_fmt: "https://usdf-rsp.slac.stanford.edu/api/datalink/links?ID=butler%3A//embargo/{id}"
  deepCoadd_calexp:
    dataproduct_type: image
    dataproduct_subtype: lsst.deepCoadd_calexp
    calib_level: 3
    obs_id_fmt: "{skymap}-{tract}-{patch}"
    o_ucd: phot.count
    access_format: "application/x-votable+xml;content=datalink"
    datalink_url_fmt: "https://usdf-rsp.slac.stanford.edu/api/datalink/links?ID=butler%3A//embargo/{id}"
  goodSeeingCoadd:
    dataproduct_type: image
    dataproduct_subtype: lsst.goodSeeingCoadd
    calib_level: 3
    obs_id_fmt: "{skymap}-{tract}-{patch}"
    o_ucd: phot.count
    access_format: "application/x-votable+xml;content=datalink"
    datalink_url_fmt: "https://usdf-rsp.slac.stanford.edu/api/datalink/links?ID=butler%3A//embargo/{id}"
  goodSeeingDiff_differenceExp:
    dataproduct_type: image
    dataproduct_subtype: lsst.goodSeeingDiff_differenceExp
    calib_level: 3
    obs_id_fmt: "{records[visit].name}-{records[detector].full_name}"
    o_ucd: phot.count
    access_format: "application/x-votable+xml;content=datalink"
    datalink_url_fmt: "https://usdf-rsp.slac.stanford.edu/api/datalink/links?ID=butler%3A//embargo/{id}"
extra_columns:
  lsst_visit:
    template: "{visit}"
    type: "int"
  lsst_detector:
    template: "{detector}"
    type: "int"
  lsst_tract:
    template: "{tract}"
    type: "int"
  lsst_patch:
    template: "{patch}"
    type: "int"
  lsst_band:
    template: "{band}"
    type: "string"
  lsst_filter:
    template: "{physical_filter}"
    type: "string"
spectral_ranges:
  "u": [330.0e-9, 400.0e-9]
  "g": [402.0e-9, 552.0e-9]
  "r": [552.0e-9, 691.0e-9]
  "i": [691.0e-9, 818.0e-9]
  "z": [818.0e-9, 922.0e-9]
  "y": [970.0e-9, 1060.0e-9]
